name: "Docker Check"
author: "XXXXXXXXXXXX"
description: "XXXXXXXXXXXX"
inputs:
  dockerfile:
    description: "Path for the Dockerfile to analyse"
    required: true
    default: ""
branding:
  icon: "terminal"
  color: "gray-dark"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v7
      name: Install python
      with:
        python-version: '3.14'
        cache: 'pip'

    - name: Install python requirements
      shell: bash
      run: pip install -r src/requirements.txt

    - name: Run the check
      id: check
      shell: bash
      env:
        DOCKERFILE: ${{ inputs.dockerfile }}
      run: pip install -r src/requirements.txt

    - name: Exit action
      shell: bash
      run: exit ${{steps.check.outputs.statuscode}}
